### PR TITLE
Add Github workflow for creating Github releases

### PR DESCRIPTION
**Pull request by michael-the1**
Add Github workflow for creating Github releases from git tags.

### CODE REVIEW

**Comment by michael-the1** [comment]
I'm changing the tag setup from `diepvries/X.Y.Z` to the more standard `vX.Y.Z` which is recommended by Github and looks good in release names, e.g. "diepvries v0.9.3".

**Review by matthieucan — COMMENTED** [review]
Super nice! WDYT of merging those steps with the steps in `pypi-build-and-deploy`?

**Comment by michael-the1** [comment]
> Super nice! WDYT of merging those steps with the steps in `pypi-build-and-deploy`?

For me it's fine either way. The only difference is that the `pypi-build-and-deploy` would get an extra write permission that it technically speaking doesn't need.

**Comment by michael-the1** [comment]
> Super nice! WDYT of merging those steps with the steps in `pypi-build-and-deploy`?

Works for me!

**Review by matthieucan — APPROVED** [review]
Perfect 👌

**Review by dlouseiro — APPROVED** [review]
LGTM! let's go

**Pull request merged**
